name: Site Bug
about: Report a bug on the Docs site
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value:
        Thanks for taking the time to submit this issue. Your input is really appreciated.
  - type: textarea
    id: expected-behavior
    attributes:
        label: Expected behavior
        description: What did you expect to happen?
        placeholder: Tell us what you see!
  - type: textarea
    id: actual-behavior
    attributes:
        label: Actual behavior
        description: What actually happened?
        placeholder: Tell us what you wanted to see!
  - type: textarea
    id: steps
    attributes:
        label: Steps
        description: Steps to reproduce the problem
        placeholder: 1. Add step.
  - type: textarea
    id: resolution
    attributes:
        label: Suggested resolution
        description: Do you have thoughts on how this should be addressed?
        placeholder: Leave blank if this does not apply or you have nothing to add.
  - type: textarea
    id: information
    attributes:
        label: Additional information
        description: Add any other context about the problem here.
        placeholder: Leave this section blank if it does not apply or you have nothing to add.



