name: Ping routes [PREVIEW]

# Run when a PR is opened or synchronized
on:
  push
  # pull_request:
  #   types: [opened, synchronize]

jobs:
  ping-routes:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@v1.2.0
        id: waitForVercelPreviewDeployment
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 360 # seconds

      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile

      - name: Run tests against preview url
        id: integration
        # test against Preview URL when it is a PR
        run: TEST_URL=${{ steps.waitForVercelPreviewDeployment.outputs.url }} pnpm test:ci
